import QAlgBench.Base
import Mathlib.Analysis.Asymptotics.Defs
import Mathlib.GroupTheory.Perm.Centralizer

/-!
# Weak Fourier sampling for a transposition in `Sₙ`

This file formalizes the finite probability distributions, the transposition
subgroup, the relevant conjugacy class, and the single- and multiple-sample
claims in the benchmark problem.
-/

open scoped BigOperators

namespace QAlgFormalized.WeakFourierSamplingTranspositionSn

/-- A real-valued probability distribution on a finite outcome type. -/
structure FiniteProbabilityDistribution (Ω : Type*) [Fintype Ω] where
  probability : Ω → ℝ
  probability_nonneg : ∀ ω, 0 ≤ probability ω
  sum_probability : ∑ ω, probability ω = 1

/-- Total-variation distance, with the normalization used in the problem. -/
noncomputable def totalVariation {Ω : Type*} [Fintype Ω]
    (P Q : FiniteProbabilityDistribution Ω) : ℝ :=
  (1 / 2 : ℝ) * ∑ ω, |P.probability ω - Q.probability ω|

/-- The distribution of `m` independent samples from `P`. -/
noncomputable def FiniteProbabilityDistribution.iidPower
    {Ω : Type*} [Fintype Ω] (P : FiniteProbabilityDistribution Ω) (m : ℕ) :
    FiniteProbabilityDistribution (Fin m → Ω) where
  probability x := ∏ i, P.probability (x i)
  probability_nonneg x := by
    exact Finset.prod_nonneg fun i _ => P.probability_nonneg (x i)
  sum_probability := by
    simpa only [P.sum_probability, one_pow] using
      (Fintype.sum_pow (f := P.probability) m).symm

/-- The points labelled `1` and `2` in the statement, represented as `0` and
`1` in Lean's zero-based type `Fin n`. -/
def firstPoint (n : ℕ) (hn : 2 ≤ n) : Fin n :=
  ⟨0, by omega⟩

def secondPoint (n : ℕ) (hn : 2 ≤ n) : Fin n :=
  ⟨1, by omega⟩

/-- The transposition `(1 2)` in `Sₙ` (using zero-based `Fin n`). -/
def transposition (n : ℕ) (hn : 2 ≤ n) : Equiv.Perm (Fin n) :=
  Equiv.swap (firstPoint n hn) (secondPoint n hn)

/-- The hidden subgroup generated by the transposition. It is proved below to
have the carrier `{1, π}`. -/
def transpositionSubgroup (n : ℕ) (hn : 2 ≤ n) :
    Subgroup (Equiv.Perm (Fin n)) :=
  Subgroup.closure {transposition n hn}

/-- The subgroup generated by a transposition consists exactly of the identity
and that transposition. -/
theorem transpositionSubgroup_carrier (n : ℕ) (hn : 2 ≤ n) :
    (transpositionSubgroup n hn : Set (Equiv.Perm (Fin n))) =
      {1, transposition n hn} := by
  let π := transposition n hn
  have hsq : π * π = 1 := by
    exact Equiv.swap_mul_self (firstPoint n hn) (secondPoint n hn)
  have hinv : π⁻¹ = π := by
    exact Equiv.swap_inv (firstPoint n hn) (secondPoint n hn)
  let H : Subgroup (Equiv.Perm (Fin n)) :=
    { carrier := {1, π}
      one_mem' := by simp
      mul_mem' := by
        intro a b ha hb
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha hb ⊢
        rcases ha with rfl | rfl <;> rcases hb with rfl | rfl
        all_goals simp [hsq]
      inv_mem' := by
        intro a ha
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha ⊢
        rcases ha with rfl | rfl
        · simp
        · exact Or.inr hinv }
  change (↑(Subgroup.closure {π}) : Set (Equiv.Perm (Fin n))) = {1, π}
  change (↑(Subgroup.closure {π}) : Set (Equiv.Perm (Fin n))) = (H : Set _)
  congr 1
  apply le_antisymm
  · exact (Subgroup.closure_le H).2 (by simp [H])
  · intro x hx
    simp only [H] at hx
    rcases hx with rfl | rfl
    · exact Subgroup.one_mem _
    · exact Subgroup.subset_closure (by simp)

/-- Abstract data for weak Fourier sampling on `Sₙ`: `Dual` represents
`\widehat{Sₙ}`, and `distribution H` is the weak Fourier-sampling distribution
for the hidden subgroup `H`. The source problem uses no formula for this map,
so it is retained as governing data. -/
structure WeakFourierSamplingModel (n : ℕ) (Dual : Type*) [Fintype Dual] where
  distribution :
    Subgroup (Equiv.Perm (Fin n)) → FiniteProbabilityDistribution Dual

/-- Weak Fourier sampling for the trivial hidden subgroup. -/
noncomputable def WeakFourierSamplingModel.trivialDistribution
    {n : ℕ} {Dual : Type*} [Fintype Dual]
    (M : WeakFourierSamplingModel n Dual) :
    FiniteProbabilityDistribution Dual :=
  M.distribution ⊥

/-- Weak Fourier sampling for `H_π = {1, π}`. -/
noncomputable def WeakFourierSamplingModel.transpositionDistribution
    {n : ℕ} {Dual : Type*} [Fintype Dual]
    (M : WeakFourierSamplingModel n Dual) (hn : 2 ≤ n) :
    FiniteProbabilityDistribution Dual :=
  M.distribution (transpositionSubgroup n hn)

/-- The conjugacy class of the transposition, bundled as a finite type. -/
def TranspositionConjugacyClass (n : ℕ) (hn : 2 ≤ n) : Type :=
  {τ : Equiv.Perm (Fin n) // IsConj (transposition n hn) τ}

/-- There are exactly `n(n-1)/2` transpositions in `Sₙ`, hence this is the
exact cardinality of the conjugacy class of `(1 2)`. -/
theorem transpositionConjugacyClass_card (n : ℕ) (hn : 2 ≤ n) :
    Nat.card (TranspositionConjugacyClass n hn) = n * (n - 1) / 2 := by
  classical
  have hab : firstPoint n hn ≠ secondPoint n hn := by
    simp [firstPoint, secondPoint, Fin.ext_iff]
  have hcycle : (transposition n hn).cycleType = {2} := by
    simpa [transposition, Equiv.Perm.card_support_swap hab] using
      (Equiv.Perm.isCycle_swap hab).cycleType
  change Nat.card {τ : Equiv.Perm (Fin n) //
    IsConj (transposition n hn) τ} = _
  simp_rw [Equiv.Perm.isConj_iff_cycleType_eq, hcycle, eq_comm]
  rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
  have htwo : 2 ≤ Fintype.card (Fin n) := by simpa using hn
  have hcard := Equiv.Perm.card_of_cycleType_singleton
    (α := Fin n) (n := 2) (by omega) htwo
  simpa [eq_comm, Nat.choose_two_right] using hcard.symm

/-- The assumed conjugacy-class bound gives the requested explicit
single-sample bound. -/
theorem weakFourierSampling_singleSample_bound
    (n : ℕ) (hn : 2 ≤ n) {Dual : Type*} [Fintype Dual]
    (M : WeakFourierSamplingModel n Dual)
    (hconj :
      totalVariation M.trivialDistribution (M.transpositionDistribution hn) ≤
        1 / (2 * Real.sqrt (Nat.card (TranspositionConjugacyClass n hn) : ℝ))) :
    totalVariation M.trivialDistribution (M.transpositionDistribution hn) ≤
      1 / Real.sqrt (2 * (n : ℝ) * ((n : ℝ) - 1)) := by
  have hcast : (Nat.card (TranspositionConjugacyClass n hn) : ℝ) =
      (n : ℝ) * ((n : ℝ) - 1) / 2 := by
    rw [transpositionConjugacyClass_card n hn,
      Nat.cast_div_charZero (Nat.two_dvd_mul_sub_one n), Nat.cast_mul,
      Nat.cast_sub (by omega : 1 ≤ n)]
    norm_num
  have hsqrt4 : Real.sqrt (4 : ℝ) = 2 := by
    rw [show (4 : ℝ) = 2 ^ 2 by norm_num, Real.sqrt_sq (by norm_num)]
  calc
    totalVariation M.trivialDistribution (M.transpositionDistribution hn) ≤
        1 / (2 * Real.sqrt
          (Nat.card (TranspositionConjugacyClass n hn) : ℝ)) := hconj
    _ = 1 / Real.sqrt (2 * (n : ℝ) * ((n : ℝ) - 1)) := by
      rw [show 2 * (n : ℝ) * ((n : ℝ) - 1) =
          4 * (Nat.card (TranspositionConjugacyClass n hn) : ℝ) by
        rw [hcast]
        ring]
      rw [Real.sqrt_mul (by positivity : (0 : ℝ) ≤ 4), hsqrt4]

/-- Total variation of independent product distributions is at most the number
of samples times the one-sample total variation. -/
theorem totalVariation_iidPower_le
    {Ω : Type*} [Fintype Ω] (P Q : FiniteProbabilityDistribution Ω) (m : ℕ) :
    totalVariation (P.iidPower m) (Q.iidPower m) ≤
      (m : ℝ) * totalVariation P Q := by
  unfold totalVariation
  let L : ℕ → ℝ := fun k =>
    ∑ x : Fin k → Ω,
      |(P.iidPower k).probability x - (Q.iidPower k).probability x|
  have hone : L 1 = ∑ a : Ω, |P.probability a - Q.probability a| := by
    dsimp only [L]
    simp only [FiniteProbabilityDistribution.iidPower, Fin.prod_univ_one]
    exact Fintype.sum_equiv (Equiv.funUnique (Fin 1) Ω) _ _ (fun _ => rfl)
  have hsplit (k : ℕ) : L (k + 1) ≤ L k + L 1 := by
    have heq : L (k + 1) =
        ∑ z : (Fin k → Ω) × Ω,
          |(P.iidPower k).probability z.1 * P.probability z.2 -
            (Q.iidPower k).probability z.1 * Q.probability z.2| := by
      dsimp only [L]
      apply Fintype.sum_equiv (Fin.succFunEquiv Ω k)
      intro x
      simp only [FiniteProbabilityDistribution.iidPower,
        Fin.prod_univ_castSucc]
      rfl
    rw [heq, Fintype.sum_prod_type]
    calc
      (∑ y : Fin k → Ω, ∑ a : Ω,
        |(P.iidPower k).probability y * P.probability a -
          (Q.iidPower k).probability y * Q.probability a|) ≤
          ∑ y : Fin k → Ω, ∑ a : Ω,
            (P.probability a *
                |(P.iidPower k).probability y -
                  (Q.iidPower k).probability y| +
              (Q.iidPower k).probability y *
                |P.probability a - Q.probability a|) := by
        apply Finset.sum_le_sum
        intro y hy
        apply Finset.sum_le_sum
        intro a ha
        calc
          |(P.iidPower k).probability y * P.probability a -
              (Q.iidPower k).probability y * Q.probability a| =
              |P.probability a *
                  ((P.iidPower k).probability y -
                    (Q.iidPower k).probability y) +
                (Q.iidPower k).probability y *
                  (P.probability a - Q.probability a)| := by
                    congr 1
                    ring
          _ ≤ |P.probability a *
                  ((P.iidPower k).probability y -
                    (Q.iidPower k).probability y)| +
                |(Q.iidPower k).probability y *
                  (P.probability a - Q.probability a)| := abs_add_le _ _
          _ = _ := by
            rw [abs_mul, abs_mul,
              abs_of_nonneg (P.probability_nonneg a),
              abs_of_nonneg ((Q.iidPower k).probability_nonneg y)]
      _ = L k + L 1 := by
        rw [hone]
        dsimp only [L]
        simp_rw [Finset.sum_add_distrib]
        congr 1
        · apply Finset.sum_congr rfl
          intro y hy
          rw [← Finset.sum_mul, P.sum_probability, one_mul]
        · calc
            (∑ y : Fin k → Ω, ∑ a : Ω,
                (Q.iidPower k).probability y *
                  |P.probability a - Q.probability a|) =
                ∑ y : Fin k → Ω, (Q.iidPower k).probability y *
                  (∑ a : Ω,
                    |P.probability a - Q.probability a|) := by
                      apply Finset.sum_congr rfl
                      intro y hy
                      rw [Finset.mul_sum]
            _ = ∑ a : Ω, |P.probability a - Q.probability a| := by
              rw [← Finset.sum_mul, (Q.iidPower k).sum_probability, one_mul]
  have hL : ∀ k : ℕ, L k ≤ (k : ℝ) * L 1 := by
    intro k
    induction k with
    | zero => simp [L, FiniteProbabilityDistribution.iidPower]
    | succ k ih =>
        calc
          L (k + 1) ≤ L k + L 1 := hsplit k
          _ ≤ (k : ℝ) * L 1 + L 1 := add_le_add ih le_rfl
          _ = ((k + 1 : ℕ) : ℝ) * L 1 := by
            push_cast
            ring
  have h := hL m
  change (1 / 2 : ℝ) * L m ≤
    (m : ℝ) * ((1 / 2 : ℝ) *
      ∑ a : Ω, |P.probability a - Q.probability a|)
  calc
    (1 / 2 : ℝ) * L m ≤ (1 / 2 : ℝ) * ((m : ℝ) * L 1) :=
      mul_le_mul_of_nonneg_left h (by norm_num)
    _ = (m : ℝ) * ((1 / 2 : ℝ) *
        ∑ a : Ω, |P.probability a - Q.probability a|) := by
      rw [hone]
      ring

/-- If `m` samples have constant distinguishing advantage `δ`, then the TV
bounds force the displayed pointwise lower bound on `m`. -/
theorem necessarySampleCount_lowerBound
    (n : ℕ) (hn : 2 ≤ n) {Dual : Type*} [Fintype Dual]
    (M : WeakFourierSamplingModel n Dual)
    (m : ℕ) (δ : ℝ) (hδ : 0 < δ)
    (hconj :
      totalVariation M.trivialDistribution (M.transpositionDistribution hn) ≤
        1 / (2 * Real.sqrt (Nat.card (TranspositionConjugacyClass n hn) : ℝ)))
    (hadvantage :
      δ ≤ totalVariation (M.trivialDistribution.iidPower m)
        ((M.transpositionDistribution hn).iidPower m)) :
    δ * Real.sqrt (2 * (n : ℝ) * ((n : ℝ) - 1)) ≤ (m : ℝ) := by
  have hnR : (1 : ℝ) < (n : ℝ) := by
    exact_mod_cast (show 1 < n by omega)
  have hspos : 0 < Real.sqrt (2 * (n : ℝ) * ((n : ℝ) - 1)) := by
    positivity
  apply (le_div_iff₀ hspos).mp
  calc
    δ ≤ totalVariation (M.trivialDistribution.iidPower m)
        ((M.transpositionDistribution hn).iidPower m) := hadvantage
    _ ≤ (m : ℝ) * totalVariation M.trivialDistribution
        (M.transpositionDistribution hn) := totalVariation_iidPower_le _ _ _
    _ ≤ (m : ℝ) *
        (1 / Real.sqrt (2 * (n : ℝ) * ((n : ℝ) - 1))) := by
      gcongr
      exact weakFourierSampling_singleSample_bound n hn M hconj
    _ = (m : ℝ) /
        Real.sqrt (2 * (n : ℝ) * ((n : ℝ) - 1)) := by ring

/-- A fixed positive distinguishing advantage for a family of instances
requires `Ω(n)` samples. Following the conventional meaning of lower asymptotic
bounds, the conclusion states `n = O(sampleCount n)`. -/
theorem necessarySampleCount_isOmega
    (Dual : ℕ → Type*) [∀ n, Fintype (Dual n)]
    (M : (n : ℕ) → WeakFourierSamplingModel n (Dual n))
    (sampleCount : ℕ → ℕ) (δ : ℝ) (hδ : 0 < δ)
    (hconj : ∀ n (hn : 2 ≤ n),
      totalVariation (M n).trivialDistribution
          ((M n).transpositionDistribution hn) ≤
        1 / (2 * Real.sqrt
          (Nat.card (TranspositionConjugacyClass n hn) : ℝ)))
    (hadvantage : ∀ᶠ n in Filter.atTop, ∀ hn : 2 ≤ n,
      δ ≤ totalVariation ((M n).trivialDistribution.iidPower (sampleCount n))
        (((M n).transpositionDistribution hn).iidPower (sampleCount n))) :
    Asymptotics.IsBigO Filter.atTop (fun n : ℕ => (n : ℝ))
      (fun n : ℕ => (sampleCount n : ℝ)) := by
  refine Asymptotics.IsBigO.of_bound δ⁻¹ ?_
  filter_upwards [hadvantage, Filter.eventually_ge_atTop 2] with n hadv hn
  have hlower := necessarySampleCount_lowerBound n hn (M n) (sampleCount n)
    δ hδ (hconj n hn) (hadv hn)
  have hnR : (2 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
  have hn0 : (0 : ℝ) ≤ (n : ℝ) := by positivity
  have hnm1 : (0 : ℝ) ≤ (n : ℝ) - 1 := by linarith
  have harg0 : (0 : ℝ) ≤ 2 * (n : ℝ) * ((n : ℝ) - 1) := by
    positivity
  have hsqrt :
      (n : ℝ) ≤ Real.sqrt (2 * (n : ℝ) * ((n : ℝ) - 1)) := by
    apply (Real.le_sqrt hn0 harg0).2
    nlinarith [mul_nonneg hn0 (sub_nonneg.mpr hnR)]
  have hlinear : δ * (n : ℝ) ≤ (sampleCount n : ℝ) :=
    (mul_le_mul_of_nonneg_left hsqrt hδ.le).trans hlower
  have hdiv : (n : ℝ) ≤ (sampleCount n : ℝ) / δ :=
    (le_div_iff₀ hδ).2 (by simpa only [mul_comm] using hlinear)
  have hnle : (n : ℝ) ≤ δ⁻¹ * (sampleCount n : ℝ) := by
    calc
      (n : ℝ) ≤ (sampleCount n : ℝ) / δ := hdiv
      _ = δ⁻¹ * (sampleCount n : ℝ) := by ring
  rw [Real.norm_eq_abs, Real.norm_eq_abs,
    abs_of_nonneg hn0,
    abs_of_nonneg (by positivity : (0 : ℝ) ≤ (sampleCount n : ℝ))]
  exact hnle

end QAlgFormalized.WeakFourierSamplingTranspositionSn
